# Generated by Django 5.2.3 on 2025-07-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Is_owner', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100, unique=True)),
                ('room_name', models.CharField(max_length=200, unique=True)),
                ('room_capacity', models.IntegerField(unique=True)),
                ('room_description', models.TextField(unique=True)),
                ('room_image', models.CharField(max_length=255, unique=True)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('room_location', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('rom_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('RoomListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.roomlisting', unique=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user', unique=True)),
            ],
        ),
    ]
