# Generated by Django 5.2.3 on 2025-07-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
    ]
