# Generated by Django 5.2.3 on 2025-08-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomlisting',
            old_name='rom_owner',
            new_name='room_owner',
        ),
    ]
