# Generated by Django 5.2.3 on 2025-07-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20250716_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='RoomListing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.roomlisting'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='rom_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
