# Generated by Django 5.2.3 on 2025-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_rom_owner_roomlisting_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
