# Generated by Django 5.2.3 on 2025-08-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='phone_no',
        ),
    ]
