# Generated by Django 5.2.3 on 2025-09-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
