# Generated by Django 5.2.3 on 2025-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Admin can flag/unflag this listing'),
        ),
    ]
