# Generated by Django 5.2.3 on 2025-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_roomlisting_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='room_image',
            field=models.CharField(max_length=755),
        ),
    ]
