# Generated by Django 5.2.3 on 2025-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_roomlisting_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='room_image',
            field=models.TextField(),
        ),
    ]
