# Generated by Django 5.2.3 on 2025-11-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_roomlisting_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
